name: Workflow Example 2
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:      
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci      
  run-tests:
    needs: checkout
    runs-on: ubuntu-latest
    steps:      
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test      
  build:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:      
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build      
  deploy:
    needs: [run-test, build]
    runs-on: ubuntu-latest
    steps:      
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
  